a:
  b:
    c: 12
  c:
    c: 12

postgres:
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: wawawa
  database: demo_fastapi
  pool_size: 30
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: wawawa
  database: demo_fastapi
rabbitmq:
  username: 'guest'
  password: 'guest'
  host: '127.0.0.1'
  port: 5672
  exchange: 'molook'
  virtual_host: 'molook-uat'
  connection_name: '[dev]-[136]-comfyui-api-server'
  ssh: 'false'
#toml1 = '2233'
toml2: '2233'
nested:
  book:
    name: '1233'