[project]
name = "demo-fastapi"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "wwfyde", email = "wwfyde@163.com" }
]
dependencies = [
    "fastapi[all]>=0.114.0",
    "pip>=24.2",
    "sqlalchemy[asyncio]>=2.0.34",
    "alembic>=1.13.2",
    "redis>=5.0.8",
    "celery>=5.4.0",
    "logfire[fastapi,psycopg,redis]>=0.52.0",
    "python-jose>=3.3.0",
    "passlib[bcrypt]>=1.7.4",
    "psycopg[asyncio,binary,pool]>=3.2.1",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "jupyterlab>=4.2.5",
    "ipython>=8.27.0",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/demo_fastapi"]
