[tool.poetry]
name = "demo-fastapi"
version = "0.1.0"
description = "a demo fastapi project for tech experiment"
authors = ["wwfyde <wwfyde@163.com>"]
readme = "README.md"
#packages = [{ include = "app" }]
package-mode = false


[tool.poetry.dependencies]
python = "^3.11"
fastapi = { extras = ["all"], version = "^0.111.0" }
sqlalchemy = "^2.0.18"
alembic = "^1.11.1"
requests = "^2.31.0"
psycopg = {extras = ["asyncio", "binary", "pool"], version = "^3.2.1"}
python-jose = { extras = ["cryptography"], version = "^3.3.0" }
passlib = { extras = ["bcrypt"], version = "^1.7.4" }
python-dotenv = "^1.0.0"
pydantic-settings = "^2.1.0"
redis = "^5.0.1"
celery = "^5.3.6"
greenlet = "^3.0.3"
ruff = "^0.4.2"
opentelemetry-api = "^1.24.0"
opentelemetry-sdk = "^1.24.0"
opentelemetry-instrumentation-asgi = "^0.45b0"
opentelemetry-instrumentation-fastapi = "^0.45b0"
logfire = { extras = ["fastapi", "psycopg", "redis"], version = "^0.29.0" }


[tool.poetry.group.dev.dependencies]
ipython = "^8.22.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
