"""add cloumn description2 for Item

Revision ID: 75f510d2e656
Revises: 
Create Date: 2023-10-29 16:03:20.514932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75f510d2e656'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('description2', sa.String(), nullable=True))
    op.create_index(op.f('ix_items_description2'), 'items', ['description2'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_description2'), table_name='items')
    op.drop_column('items', 'description2')
    # ### end Alembic commands ###
